### ISSUE TITLE
Very cool work

### ISSUE THREAD

**Issue by ggoodman** [AlejoFernandez/webtask-api-boilerplate#1]
I'm one of the people working on the webtask platform and it's very neat to see you take some of our ideas and run (very far) with them.

In your roadmap you hint that you would like to remove the dependency on `wt-cli`. Perhaps you might consider taking a look at: https://github.com/auth0/sandboxjs. I would suggest sticking to `1.x` because I'm making lots of changes to `2.x` right now.

Keep up the great work and please let us know if you have any feedback on working with the platform. You can chat with us at http://chat.webtask.io/ or me personally at geoff at auth dot com.

**Comment by alejofernandez** [comment]
Thank you @ggoodman and nice to meet you! Also thank you for pointing me to `sandboxjs`, I believe that's exactly what I'm looking for.

It's really amazing the things you can do using webtask.io, and everything works as expected, nice and easy, great tutorials, articles and documentation, I really like it very much. 

I've collected some feedback, actually minor feedback, so I'll join the chat and post it there.

Thanks again for stopping by, and of course I accept any suggestion you may have for the roadmap of this project.

**Comment by alejofernandez** [comment]
@ggoodman, `wt-cli` dependency removed thanks to `sandboxjs`.
Please check https://github.com/AlejoFernandez/webtask-api-boilerplate/commit/1161b610cbe1db346e54704df8cca33a15fd92a1
Cheers!

**Comment by ggoodman** [comment]
Hey that's great! If you have a chance at some point, I'd love to hear any constructive criticism you might have with regards to the `sandboxjs` documentation and api.
